### ISSUE TITLE
new version of graphic

### ISSUE THREAD

**Issue by vakaobr** [vinicelms/sonarqube-prometheus-exporter#5]
Hello there,

Did some changes in original graphic, and added some extra options, could be found [here.](https://gist.github.com/vakaobr/aac8881e5f914bdaa5fd3736fa584064)

The extra plugin I'm using in grafana to generate the graphics are available [here.](https://grafana.com/grafana/plugins/grafana-polystat-panel)

**Comment by vinicelms** [comment]
Hello, @vakaobr!

Forward a PR with a new dashboard. If you can also include a screenshot of your dashboard in the project's README.md, it also helps a lot.

Thanks!
